name: Docker Image CI

on:
  push:
    branches: [ "atl285-docker-workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd docker && docker build --build-arg "VERSION=3.5.6.1" --file ./Dockerfile --tag my-image-name:$(date +%s) .
